package com.riverasmotor.harvisa01;

import android.app.*;import android.content.*;import android.os.*;import android.speech.tts.TextToSpeech;import androidx.core.app.NotificationCompat;import org.json.*;import org.vosk.Model;import org.vosk.Recognizer;import org.vosk.android.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class HarvisVoiceService extends Service implements RecognitionListener, TextToSpeech.OnInitListener {
 static final String CH="harvis_voice"; static final int ID=1701; Model model; Recognizer rec; SpeechService speech; TextToSpeech tts; boolean running=true;
 @Override public void onCreate(){super.onCreate();createChannel();startForeground(ID,note("HARVIS // VOZ EN SEGUNDO PLANO"));tts=new TextToSpeech(this,this);StorageService.unpack(this,"model-es","model-es",m->{model=m;startListening();},e->update("HARVIS // VOSK ERROR"));}
 @Override public int onStartCommand(Intent i,int f,int id){running=true;if(model!=null&&speech==null)startListening();return START_STICKY;}
 void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CH,"HARVIS Voice",NotificationManager.IMPORTANCE_LOW);c.setDescription("HARVIS activo en segundo plano");getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 Notification note(String s){Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,open,Build.VERSION.SDK_INT>=23?PendingIntent.FLAG_IMMUTABLE:0);return new NotificationCompat.Builder(this,CH).setContentTitle("HARVIS MARK I").setContentText(s).setSmallIcon(android.R.drawable.ic_btn_speak_now).setOngoing(true).setContentIntent(pi).build();}
 void update(String s){((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(ID,note(s));}
 void startListening(){try{stopListening();rec=new Recognizer(model,16000f);speech=new SpeechService(rec,16000f);speech.startListening(this);update("HARVIS // ESCUCHANDO");}catch(Exception e){update("HARVIS // AUDIO ERROR");}}
 void stopListening(){if(speech!=null){speech.stop();speech.shutdown();speech=null;}if(rec!=null){rec.close();rec=null;}}
 @Override public void onResult(String h){try{String text=new JSONObject(h).optString("text","").trim();if(!text.isEmpty()){stopListening();update("HARVIS // PROCESANDO");ask(text);}}catch(Exception e){restart();}}
 @Override public void onFinalResult(String h){if(speech!=null)onResult(h);}@Override public void onPartialResult(String h){}@Override public void onError(Exception e){restart();}@Override public void onTimeout(){restart();}
 void restart(){if(running)new Handler(getMainLooper()).postDelayed(()->{if(model!=null)startListening();},700);}
 void ask(String text){new Thread(()->{try{SharedPreferences p=getSharedPreferences("harvis",0);String root=p.getString("url","").replaceAll("/+$","");String tok=p.getString("token","").replaceAll("\\s+","");HttpURLConnection c=(HttpURLConnection)new URL(root+"/v1/chat").openConnection();c.setConnectTimeout(5000);c.setReadTimeout(120000);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");if(!tok.isEmpty()){c.setRequestProperty("Authorization","Bearer "+tok);c.setRequestProperty("X-HARVIS-Token",tok);}JSONObject j=new JSONObject();j.put("message",text);j.put("text",text);j.put("device","android-a01-background-vosk");try(OutputStream o=c.getOutputStream()){o.write(j.toString().getBytes(StandardCharsets.UTF_8));}InputStream in=c.getResponseCode()<400?c.getInputStream():c.getErrorStream();BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String l;while((l=r.readLine())!=null)b.append(l);JSONObject x=new JSONObject(b.toString());String a=x.optString("answer",x.optString("response",x.optString("text","")));String spoken=clean(a);new Handler(getMainLooper()).post(()->{update("HARVIS // HABLANDO");if(tts!=null&&!spoken.isEmpty())tts.speak(spoken,TextToSpeech.QUEUE_FLUSH,null,"bg");restart();});}catch(Exception e){update("HARVIS // SIN ENLACE");restart();}}).start();}
 String clean(String s){StringBuilder b=new StringBuilder();boolean src=false;for(String line:s.split("\\r?\\n")){String t=line.trim(),u=t.toUpperCase(Locale.ROOT);if(u.startsWith("FUENTE")||u.startsWith("SOURCE")||u.startsWith("REFERENCIA")){src=true;continue;}if(src){if(t.isEmpty())src=false;else continue;}t=t.replaceAll("https?://\\S+|www\\.\\S+","").replaceAll("[`*_#~|<>\\[\\]{}]+"," ").replaceAll("/{2,}|\\\\{2,}"," ").replaceAll("\\s+"," ").trim();if(!t.isEmpty())b.append(t).append(". ");}return b.toString().trim();}
 @Override public void onInit(int s){if(s==TextToSpeech.SUCCESS){tts.setLanguage(new Locale("es","AR"));tts.setSpeechRate(1.08f);tts.setPitch(1f);}}
 @Override public IBinder onBind(Intent i){return null;}@Override public void onDestroy(){running=false;stopListening();if(model!=null)model.close();if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
}