package com.riverasmotor.harvisa01;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.provider.OpenableColumns;import android.net.Uri;import android.media.AudioManager;import android.bluetooth.BluetoothAdapter;import android.speech.RecognizerIntent;import android.speech.tts.TextToSpeech;import android.view.View;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class MainActivity extends Activity implements TextToSpeech.OnInitListener{
 EditText baseUrl,token,message;TextView status,chat,orb;ScrollView scroll;LinearLayout settings;TextToSpeech tts;AudioManager audio;final int VOICE=42,FILE=43;Handler retry=new Handler();boolean stopped=false;
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);baseUrl=findViewById(R.id.baseUrl);token=findViewById(R.id.token);message=findViewById(R.id.message);status=findViewById(R.id.status);chat=findViewById(R.id.chat);orb=findViewById(R.id.orb);scroll=findViewById(R.id.scroll);settings=findViewById(R.id.settings);SharedPreferences p=getSharedPreferences("harvis",0);baseUrl.setText(p.getString("url","http://192.168.0.57:8765"));token.setText(p.getString("token",""));tts=new TextToSpeech(this,this);audio=(AudioManager)getSystemService(AUDIO_SERVICE);
  findViewById(R.id.config).setOnClickListener(v->settings.setVisibility(settings.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));findViewById(R.id.connect).setOnClickListener(v->{stopped=false;health(true);settings.setVisibility(View.GONE);});findViewById(R.id.send).setOnClickListener(v->send());findViewById(R.id.attach).setOnClickListener(v->pickFile());findViewById(R.id.mic).setOnClickListener(v->listen());findViewById(R.id.audio).setOnClickListener(v->routeBluetooth(true));findViewById(R.id.stop).setOnClickListener(v->{stopped=true;if(tts!=null)tts.stop();stopBluetooth();state("CORE // PAUSA","◉\n────────");});health(true);
 }
 @Override public void onInit(int s){if(s==TextToSpeech.SUCCESS){tts.setLanguage(new Locale("es","AR"));tts.setSpeechRate(1.02f);}}
 void save(){getSharedPreferences("harvis",0).edit().putString("url",baseUrl.getText().toString().trim()).putString("token",token.getText().toString()).apply();}
 HttpURLConnection conn(String path,String method)throws Exception{String root=baseUrl.getText().toString().trim().replaceAll("/+$","");if(root.length()==0)throw new Exception("Falta URL del Core");HttpURLConnection c=(HttpURLConnection)new URL(root+path).openConnection();c.setConnectTimeout(4500);c.setReadTimeout(120000);c.setRequestMethod(method);String t=token.getText().toString().trim();if(!t.isEmpty()){c.setRequestProperty("Authorization","Bearer "+t);c.setRequestProperty("X-HARVIS-Token",t);}return c;}
 void health(boolean load){save();state("CORE // CONECTANDO","◉\n· · · · ·");new Thread(()->{try{HttpURLConnection c=conn("/health","GET");String s=read(c);if(c.getResponseCode()<400){ui(()->{stopped=false;state("CORE // ONLINE","◉\n╱╲╱╲╱╲╱╲");routeBluetooth(false);});if(load)bootstrap();}else fail("HTTP "+c.getResponseCode()+" "+s);}catch(Exception e){fail(e.getMessage());}}).start();}
 void bootstrap(){new Thread(()->{try{HttpURLConnection c=conn("/v1/bootstrap","GET");String s=read(c);if(c.getResponseCode()>=400)return;JSONObject j=new JSONObject(s);JSONArray h=j.optJSONArray("history");StringBuilder b=new StringBuilder();if(h!=null){int start=Math.max(0,h.length()-14);for(int i=start;i<h.length();i++){JSONObject x=h.optJSONObject(i);if(x==null)continue;String role=x.optString("role"),content=x.optString("content",x.optString("text",""));b.append("user".equals(role)?"VOS  // ":"HARVIS // ").append(content).append("\n\n");}}ui(()->{chat.setText(b.toString());bottom();});}catch(Exception ignored){}}).start();}
 void send(){String m=message.getText().toString().trim();if(m.isEmpty()||stopped)return;save();message.setText("");append("VOS  // "+m+"\n\n");state("CORE // PROCESANDO","◉\n··╱╲··╱╲··");new Thread(()->{try{JSONObject j=new JSONObject();j.put("message",m);j.put("text",m);j.put("device","android-a01-mark1");HttpURLConnection c=conn("/v1/chat","POST");c.setRequestProperty("Content-Type","application/json; charset=utf-8");c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(j.toString().getBytes(StandardCharsets.UTF_8));}String raw=read(c);if(c.getResponseCode()>=400)throw new Exception("HTTP "+c.getResponseCode()+" "+raw);JSONObject r=new JSONObject(raw);String a=r.optString("answer",r.optString("response",r.optString("text","")));if(a.trim().isEmpty())a=raw;final String ans=a;ui(()->{append("HARVIS // "+ans+"\n\n");state("AUDIO // HABLANDO","◉\n╱╲╱╲╱╲╱╲");routeBluetooth(false);if(tts!=null)tts.speak(ans,TextToSpeech.QUEUE_FLUSH,null,"harvis");});}catch(Exception e){fail(e.getMessage());}}).start();}
 void pickFile(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,FILE);}
 String fileName(Uri u){String n="archivo";Cursor c=null;try{c=getContentResolver().query(u,null,null,null,null);if(c!=null&&c.moveToFirst()){int x=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(x>=0)n=c.getString(x);}}finally{if(c!=null)c.close();}return n;}
 void upload(Uri u){final String name=fileName(u);append("VOS  // [ARCHIVO] "+name+"\n\n");state("CORE // SUBIENDO ARCHIVO","◉\n··╱╲··╱╲··");new Thread(()->{try{String boundary="----HARVIS"+System.currentTimeMillis();HttpURLConnection c=conn("/v1/files/upload","POST");c.setRequestProperty("Content-Type","multipart/form-data; boundary="+boundary);c.setDoOutput(true);try(DataOutputStream o=new DataOutputStream(c.getOutputStream());InputStream in=getContentResolver().openInputStream(u)){o.writeBytes("--"+boundary+"\r\n");o.writeBytes("Content-Disposition: form-data; name=\"file\"; filename=\""+name.replace("\"","_")+"\"\r\n");String mime=getContentResolver().getType(u);o.writeBytes("Content-Type: "+(mime==null?"application/octet-stream":mime)+"\r\n\r\n");byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)o.write(buf,0,n);o.writeBytes("\r\n--"+boundary+"--\r\n");o.flush();}String raw=read(c);if(c.getResponseCode()>=400)throw new Exception("HTTP "+c.getResponseCode()+" "+raw);append("HARVIS // Archivo recibido por el Core: "+name+"\n\n");state("CORE // ONLINE","◉\n╱╲╱╲╱╲╱╲");}catch(Exception e){fail("Archivo "+name+": "+e.getMessage());}}).start();}
 void listen(){if(stopped)stopped=false;if(Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.RECORD_AUDIO")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.RECORD_AUDIO"},7);return;}routeBluetooth(false);try{Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"es-AR");i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,false);state("AUDIO // ESCUCHANDO","◉\n╲╱╲╱╲╱╲╱");startActivityForResult(i,VOICE);}catch(Exception e){append("SYSTEM // Reconocimiento de voz no disponible.\n");}}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==FILE&&c==RESULT_OK&&d!=null&&d.getData()!=null){upload(d.getData());return;}if(r==VOICE&&c==RESULT_OK&&d!=null){ArrayList<String>x=d.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(x!=null&&!x.isEmpty()){message.setText(x.get(0));send();return;}}state("CORE // ONLINE","◉\n╱╲╱╲╱╲╱╲");}
 void routeBluetooth(boolean announce){try{BluetoothAdapter b=BluetoothAdapter.getDefaultAdapter();boolean bt=b!=null&&b.isEnabled();if(bt){audio.setMode(AudioManager.MODE_IN_COMMUNICATION);audio.startBluetoothSco();audio.setBluetoothScoOn(true);}Button v=findViewById(R.id.audio);v.setText(bt?"AUDIO // BLUETOOTH":"AUDIO // TELÉFONO");if(announce)Toast.makeText(this,bt?"Bluetooth de audio solicitado":"Bluetooth no activo",Toast.LENGTH_SHORT).show();}catch(Exception e){if(announce)Toast.makeText(this,"Audio automático",Toast.LENGTH_SHORT).show();}}
 void stopBluetooth(){try{audio.setBluetoothScoOn(false);audio.stopBluetoothSco();audio.setMode(AudioManager.MODE_NORMAL);}catch(Exception ignored){}}
 String read(HttpURLConnection c)throws Exception{int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();if(in==null)return "";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);return s.toString();}
 void state(String s,String o){ui(()->{status.setText(s);orb.setText(o);});}void append(String s){ui(()->{chat.append(s);bottom();});}void bottom(){scroll.post(()->scroll.fullScroll(ScrollView.FOCUS_DOWN));}void ui(Runnable r){runOnUiThread(r);}void fail(String e){ui(()->{state("CORE // SIN ENLACE","◉\n× × × × ×");append("SYSTEM // "+e+"\n\n");if(!stopped)retry.postDelayed(()->health(false),5000);});}
 @Override protected void onResume(){super.onResume();if(baseUrl!=null&&!stopped)health(false);}@Override protected void onDestroy(){retry.removeCallbacksAndMessages(null);stopBluetooth();if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
}
