package com.riverasmotor.harvisa01;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.media.AudioManager;import android.bluetooth.BluetoothAdapter;import android.speech.tts.TextToSpeech;import android.view.View;import android.widget.*;import org.json.*;import org.vosk.Model;import org.vosk.android.RecognitionListener;import org.vosk.android.SpeechService;import org.vosk.android.StorageService;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class MainActivity extends Activity implements TextToSpeech.OnInitListener, RecognitionListener{
 EditText baseUrl,token,message;TextView status,chat,orb;ScrollView scroll;LinearLayout settings;TextToSpeech tts;AudioManager audio;Handler retry=new Handler();boolean stopped=false;Model voskModel;SpeechService speechService;
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);baseUrl=findViewById(R.id.baseUrl);token=findViewById(R.id.token);message=findViewById(R.id.message);status=findViewById(R.id.status);chat=findViewById(R.id.chat);orb=findViewById(R.id.orb);scroll=findViewById(R.id.scroll);settings=findViewById(R.id.settings);SharedPreferences p=getSharedPreferences("harvis",0);baseUrl.setText(p.getString("url","http://192.168.0.57:8765"));token.setText(p.getString("token",""));tts=new TextToSpeech(this,this);audio=(AudioManager)getSystemService(AUDIO_SERVICE);initVosk();
 findViewById(R.id.config).setOnClickListener(v->settings.setVisibility(settings.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));findViewById(R.id.connect).setOnClickListener(v->{stopped=false;health(true);settings.setVisibility(View.GONE);});findViewById(R.id.send).setOnClickListener(v->send());findViewById(R.id.mic).setOnClickListener(v->listen());findViewById(R.id.audio).setOnClickListener(v->routeBluetooth(true));findViewById(R.id.stop).setOnClickListener(v->{stopped=true;stopListening();if(tts!=null)tts.stop();stopBluetooth();state("CORE // PAUSA","◉\n────────");});health(true);}
 void initVosk(){state("VOSK // CARGANDO","◉\n· · · · ·");StorageService.unpack(this,"model-es","model-es",m->{voskModel=m;state("VOSK // LISTO","◉\n╱╲╱╲╱╲╱╲");},e->{state("VOSK // ERROR","◉\n× × × × ×");append("SYSTEM // Vosk: "+e.getMessage()+"\n\n");});}
 @Override public void onInit(int s){if(s==TextToSpeech.SUCCESS){tts.setLanguage(new Locale("es","AR"));tts.setSpeechRate(1.02f);}}
 void save(){getSharedPreferences("harvis",0).edit().putString("url",baseUrl.getText().toString().trim()).putString("token",token.getText().toString()).apply();}
 HttpURLConnection conn(String path,String method)throws Exception{String root=baseUrl.getText().toString().trim().replaceAll("/+$","");if(root.length()==0)throw new Exception("Falta URL del Core");HttpURLConnection c=(HttpURLConnection)new URL(root+path).openConnection();c.setConnectTimeout(4500);c.setReadTimeout(120000);c.setRequestMethod(method);c.setRequestProperty("Content-Type","application/json; charset=utf-8");String t=token.getText().toString().trim();if(!t.isEmpty()){c.setRequestProperty("Authorization","Bearer "+t);c.setRequestProperty("X-HARVIS-Token",t);}return c;}
 void health(boolean load){save();state("CORE // CONECTANDO","◉\n· · · · ·");new Thread(()->{try{HttpURLConnection c=conn("/health","GET");String s=read(c);if(c.getResponseCode()<400){ui(()->{stopped=false;state("CORE // ONLINE","◉\n╱╲╱╲╱╲╱╲");routeBluetooth(false);});if(load)bootstrap();}else fail("HTTP "+c.getResponseCode()+" "+s);}catch(Exception e){fail(e.getMessage());}}).start();}
 void bootstrap(){new Thread(()->{try{HttpURLConnection c=conn("/v1/bootstrap","GET");String s=read(c);if(c.getResponseCode()>=400)return;JSONObject j=new JSONObject(s);JSONArray h=j.optJSONArray("history");StringBuilder b=new StringBuilder();if(h!=null){int start=Math.max(0,h.length()-14);for(int i=start;i<h.length();i++){JSONObject x=h.optJSONObject(i);if(x==null)continue;String role=x.optString("role"),content=x.optString("content",x.optString("text",""));b.append("user".equals(role)?"VOS  // ":"HARVIS // ").append(content).append("\n\n");}}ui(()->{chat.setText(b.toString());bottom();});}catch(Exception ignored){}}).start();}
 void send(){String m=message.getText().toString().trim();if(m.isEmpty()||stopped)return;save();message.setText("");append("VOS  // "+m+"\n\n");state("CORE // PROCESANDO","◉\n··╱╲··╱╲··");new Thread(()->{try{JSONObject j=new JSONObject();j.put("message",m);j.put("text",m);j.put("device","android-a01-mark1-vosk");HttpURLConnection c=conn("/v1/chat","POST");c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(j.toString().getBytes(StandardCharsets.UTF_8));}String raw=read(c);if(c.getResponseCode()>=400)throw new Exception("HTTP "+c.getResponseCode()+" "+raw);JSONObject r=new JSONObject(raw);String a=r.optString("answer",r.optString("response",r.optString("text","")));if(a.trim().isEmpty())a=raw;final String ans=a;ui(()->{append("HARVIS // "+ans+"\n\n");state("AUDIO // HABLANDO","◉\n╱╲╱╲╱╲╱╲");routeBluetooth(false);if(tts!=null)tts.speak(ans,TextToSpeech.QUEUE_FLUSH,null,"harvis");});}catch(Exception e){fail(e.getMessage());}}).start();}
 void listen(){if(stopped)stopped=false;if(Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.RECORD_AUDIO")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.RECORD_AUDIO"},7);return;}if(voskModel==null){Toast.makeText(this,"Vosk todavía está cargando",Toast.LENGTH_SHORT).show();return;}stopListening();routeBluetooth(false);try{speechService=new SpeechService(voskModel,16000.0f);speechService.startListening(this);state("VOSK // ESCUCHANDO","◉\n╲╱╲╱╲╱╲╱");}catch(IOException e){append("SYSTEM // Vosk audio: "+e.getMessage()+"\n");}}
 void stopListening(){if(speechService!=null){speechService.stop();speechService.shutdown();speechService=null;}}
 @Override public void onResult(String hypothesis){try{String text=new JSONObject(hypothesis).optString("text","").trim();if(!text.isEmpty()){stopListening();message.setText(text);send();}}catch(Exception e){append("SYSTEM // Vosk resultado inválido\n");}}
 @Override public void onFinalResult(String hypothesis){if(speechService!=null)onResult(hypothesis);}
 @Override public void onPartialResult(String hypothesis){try{String p=new JSONObject(hypothesis).optString("partial","");if(!p.isEmpty())state("VOSK // "+p.toUpperCase(Locale.ROOT),"◉\n╲╱╲╱╲╱╲╱");}catch(Exception ignored){}}
 @Override public void onError(Exception e){append("SYSTEM // Vosk: "+e.getMessage()+"\n");stopListening();state("CORE // ONLINE","◉\n╱╲╱╲╱╲╱╲");}
 @Override public void onTimeout(){stopListening();state("CORE // ONLINE","◉\n╱╲╱╲╱╲╱╲");}
 void routeBluetooth(boolean announce){try{BluetoothAdapter b=BluetoothAdapter.getDefaultAdapter();boolean bt=b!=null&&b.isEnabled();if(bt){audio.setMode(AudioManager.MODE_IN_COMMUNICATION);audio.startBluetoothSco();audio.setBluetoothScoOn(true);}Button v=findViewById(R.id.audio);v.setText(bt?"AUDIO // BLUETOOTH":"AUDIO // TELÉFONO");if(announce)Toast.makeText(this,bt?"Bluetooth de audio solicitado":"Bluetooth no activo",Toast.LENGTH_SHORT).show();}catch(Exception e){if(announce)Toast.makeText(this,"Audio automático",Toast.LENGTH_SHORT).show();}}
 void stopBluetooth(){try{audio.setBluetoothScoOn(false);audio.stopBluetoothSco();audio.setMode(AudioManager.MODE_NORMAL);}catch(Exception ignored){}}
 String read(HttpURLConnection c)throws Exception{int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();if(in==null)return "";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);return s.toString();}
 void state(String s,String o){ui(()->{status.setText(s);orb.setText(o);});}void append(String s){ui(()->{chat.append(s);bottom();});}void bottom(){scroll.post(()->scroll.fullScroll(ScrollView.FOCUS_DOWN));}void ui(Runnable r){runOnUiThread(r);}void fail(String e){ui(()->{state("CORE // SIN ENLACE","◉\n× × × × ×");append("SYSTEM // "+e+"\n\n");if(!stopped)retry.postDelayed(()->health(false),5000);});}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==7&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)listen();}
 @Override protected void onResume(){super.onResume();if(baseUrl!=null&&!stopped)health(false);}@Override protected void onDestroy(){retry.removeCallbacksAndMessages(null);stopListening();stopBluetooth();if(tts!=null){tts.stop();tts.shutdown();}if(voskModel!=null)voskModel.close();super.onDestroy();}
}
