plugins {
    id 'com.android.application'
}

android {
    namespace 'com.riverasmotor.harvisa01'
    compileSdk 34

    defaultConfig {
        applicationId 'com.riverasmotor.harvisa01'
        minSdk 23
        targetSdk 29
        versionCode 4
        versionName '1.2.0-MK1-VOSK'
        ndk { abiFilters 'armeabi-v7a', 'arm64-v8a' }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'net.java.dev.jna:jna:5.18.1@aar'
    implementation 'com.alphacephei:vosk-android:0.3.75@aar'
}
